version: "3"
services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=ashal
      - MONGO_PASSWORD=ashal123
    command: yarn dev
    
  database-mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=ashal
      - MONGO_INITDB_ROOT_PASSWORD=ashal123
