version: "3"

services:
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes: 
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  
      - ./nginx:/etc/nginx/conf.d:ro  
      
  backend:
    build: .

    # ports:
    #   - "5000:5000"
    depends_on: 
      - database-mongo

  database-mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=ashal
      - MONGO_INITDB_ROOT_PASSWORD=ashal123
    volumes: 
      - mongo-db:/data/db
  
  redis:
    image: redis

volumes:
  mongo-db: