version: "3"
services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev
