version: "3"
services:
  backend:
    build:
        context: .
        args:
        NODE_ENV: development
    environment:
        - NODE_ENV=production
    command: >
    sh -c "yarn build &&
           yarn start"
